#Varibales

ENV = "dev"
EXECUTION_MODE = ["preview", "execute"]
BASE_URL = "http://dummy.com:8080"
TEST_DATA_PATH = "tests/testdata/"
FILENAME = 'node_list_dev.json'
INITFILENAME = 'initparms.json'
FILEPATH = './Artifacts/'
NODE_LIST = ["node", "hostname", "os_type", 'fileagent.enable']
FILE_ERROR= "Error reading nodes list json file"
CD_SIGN_ON = 'CDWS sign_on Successful!!'
CD_SIGN_ON_MSG = "Sign_on log line not found in logs"
CD_SIGN_ON_FAILED = 'CD Sign-on Failed!! status_code: 400'
HOST_DICT_1 = { "node": "Dummy1", "hostname": "dummy1.com", "os_type": "unix system" }
HOST_DICT_2 = { "node": "Dummy2", "hostname": "dummy2.com", "os_type": "windows system" }
HOST_DICT_3 = { "node": "Dummy3", "hostname": "dummy3.com", "os_type": "aix system" }
EXPECTED_PAYLOAD = 'y'
EXPECTED_PAYLOAD_N = 'n'
UNIX_FA_KEY = "cd.file.agent:cdfa.enable"
PAYLOAD_EXCEPTION = "pop expected at most 1 argument, got 2"
START_BACKUP_EXPECTED= 'Started backup of initparams details for node Sample'
START_BACKUP_LOG_MSG = "Start backup log line not found in logs"
COMPLETE_BACKUP_EXPECTED= 'Completed backup of initparams details for node Sample'
COMPLETE_BACKUP_LOG_MSG = "Complete Backup log line not found in logs"
TABLE_TITLE ="FileAgent status details for all nodes"
SKIP_STATUS_EXPECTED= 'Success: 1  Failed: 0  Skip:1   Update:0'
SKIPPED_STATUS_EXPECTED= 'Success: 1  Failed: 0  Skipped:1   Updated:0'
FAILED_STATUS_EXPECTED = 'Success: 0  Failed: 1'
UPDATE_STATUS_EXPECTED= 'Success: 1  Failed: 0  Skip:0   Update:1'
UPDATED_STATUS_EXPECTED= 'Success: 1  Failed: 0  Skipped:0   Updated:1'
SAME_STATUS_MSG = 'Current status matches the requested status or incorrect configured; skipping the update.'
UPDATE_STATUS_MSG= 'CD file agent status has been successfully updated for node'
UPDATE_FAILED_EXPECTED = "CD file agent status has been failed for node"
COMPLETE_BACKUP_MSG = 'Completed backup of CD artifacts for node'
COMPLETE_BACKUP_LOG = "Complete backup artifacts log line not found in logs"
PROCESS_FAILED_EXPECTED= 'Processing failed for CD FileAgent due to'
PROCESS_FAILED_LOG_MSG = "Processing failed log line not found in logs"
GEN_EXCEPTION = "Unexpected exception found during execution"
INFO_MSG = 'ℹ️ CD File Agent status naming conventions: y/n for Unix ; Y/N for Windows'
NO_DATA_MSG = "— No data —"
NOT_FOUND = 'Not found'
PROCESS_START_MSG = "Processing started for node"
PROCESS_COMPLETED_MSG = 'Processing completed for node'
INCORRECT_NODE_EXCEPTION = "node_list not configured properly. either hostname or os_type not found or invalid values for node"
HTTPERROR_EXPECTED= 'HTTPError exception during GET'
ERROR_400 = '400 Client Error'
ERROR_404 = '404 Client Error'
REQUEST_EXCEPTION = 'Request exception'
ERROR_FOUND ='Error found'
UNEXPECTED_ERROR = 'Unexpected exception found during GET'
UNEXPECTED_ERROR_CODE = 'Unexpected exception found during sign_on'
ERROR_500 = '500 Server error exception raised'
HTTP_ERROR_TEXT = 'HTTPError exception!! Text'
HTTP_ERROR_CODE = 'HTTPError exception during sign_on'
NO_ARTIFACTS = '— No Artifacts —'
ERROR_400_MSG = "400 Client Error: Not Found"
ERROR_404_MSG ="404 Client Error: Not Found"
ERROR_500_MSG="500 Server error exception raised"
RESPONSE_DATA = {"INITPARMS": [{"messageCode": 200,"message": "Init Parms data has been updated successfully"}]}



