version: 1
disable_existing_loggers: False

formatters:
  detailed:
    format: "%(asctime)s - %(message)s"
    datefmt: "%H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: detailed
    stream: ext://sys.stdout

  file:
    class: logging.FileHandler
    level: INFO
    formatter: detailed
    filename: app.log
    mode: a

loggers:
  my_app_logger:
    level: INFO
    handlers: [console, file]
    propagate: no

root:
  level: INFO
  handlers: [console, file]