#variables

LOG_FILE_PATH = "./logs"
PARENT_DIR="./Artifacts/"
NODE_CERT_BACKUP_PATH = "NODE_CERT_BACKUP/"
CERTIFICATES_PATH = "CERTIFICATES/"
CERTIFICATES =["WINDOWS_CERTIFICATE", "UNIX_CERTIFICATE", "AIX_CERTIFICATE"]
NODE_LIST_FILE = "NODE_LIST_FILE"
SYSTEMS = ["windows", "aix", "unix"]
CERT_KEYS = ("certificateLabel", "validFrom", "validTo")
POSSIBLE_CHILD_KEYS = ["children", "subCertificates", "childCertificates"]
EXPIRED_SEV_DAYS = 0
CRITICAL_SEV_DAYS = 7
WARNING_SEV_DAYS = 30
